"""The program's icon for the page: the 32 and 16 px frames of pcnotify.ico as PNG in base64.

Written by tools/make_icon.py from tools/icon_grid.py: run the tool, never edit this file by hand.
"""

PNG_32 = (
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAABlElEQVR4AWMYBcSEQFfMh/8wTEg9TB2IJqSWKHmQQf+B4OW9"
    "30DyP9ghuDSSohaXGRjipBhKiloMi3AJYDMUJIYLg4KJmNDCZR9WcZBlIINJwSA9WA0jVRBkECkWI6sF6SXVPhT1IAOQDSSH"
    "DTIDxVBSOCDN5FgK0wNKCyAzSLETrhakEWYQJTTZjsDmADlR4/8gjMtBIDkQRpYfUAeALAdhkGfgQUssA6QJ2SfksEGWgzDI"
    "LGLthasDacrVuPmfGhhkFtxgYhkgTeRa7qBe8x8Zg8wi1l64OpAmUoId5liQxaBgR8Ygs+AGk8IAaSTWEbgcADKDFDtR1II0"
    "k+IAkK9BDgHRMAwyA8VQUjkgA7A5AmYBPhqklyT7QBrogbE6CmTx4Y3f4Z4FsZHx8vmH/pOCkfWis0F2oTgCJABSBLIdRNMD"
    "g+yEOwLEoYelyHaA7Bx1wOAJAZBLQHGCHEeUsAnlFpBdIDsxMEgChJEtB/GpjTEsRhYAWQZzAIiNLEcXNshSkANANF0sRLcE"
    "ZDEIo4vTig8AgGltBNeEC2EAAAAASUVORK5CYII="
)

PNG_16 = (
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAvklEQVR4AWNABl0xH/7DMLI4iA0TB9EgPgYGSfwHgpf3fgPJ"
    "/3CDQOIgDBJElkMxAKYApIhYDNIDNwTEgWmUEzWGMTFomBzIJSA9tDEAw1o0AZDtIIzhglyNm/9JwRgGoFmEwoUZDLIZhlEM"
    "AAUGSABFFxIHZABMI4gGqQXpgWOQADkYbABI4+GN38H2gWhSMEgvA4ggRROyWpBeyg0A+QNkEsxkEJtYDNILxiANIANANFiA"
    "VAKkEYRJ1QdSDwD4O4QI07agpQAAAABJRU5ErkJggg=="
)
